[profile.default]
src = "src"
out = "out"
test = "test"
libs = ["lib"]

solc = "0.8.23"
evm_version = "paris"
use_literal_content = true

optimizer = true
optimizer_runs = 200_000

[fmt]
tab_width = 2
line_length = 120
quote_style = "double"
number_underscore = "thousands"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
